on: 
  repository_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages      
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Delete dist folder if it exist
        run: if [ -d "dist" ]; then rm -rf dist; fi

      - name: Create an empty dist folder
        run: mkdir dist

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.1'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.3
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install package dependencies
        run: pnpm install

      - name: Build
        run: pnpm build
        env: 
          PUBLIC_STORYBLOK_TOKEN: ${{ vars.PUBLIC_STORYBLOK_TOKEN }}
          VITE_STORYBLOK_TOKEN: ${{ vars.VITE_STORYBLOK_TOKEN }}

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN}}
          projectName: indomascot-astro
          directory: dist
          branch: main
          wranglerVersion: '3'
